---
# This pod mounts the nfs volume claim into /usr/share/nginx/html and
# serves a simple web page.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      role: grafana-frontend
  template:
    metadata:
      labels:
        role: grafana-frontend
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
          - name: grafana
            containerPort: 3000
        volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/var/lib/grafana"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
